# Generated by Django 5.1.6 on 2025-09-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
