# Generated by Django 5.2.7 on 2026-01-06 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistitem",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
