# Generated by Django 5.2.7 on 2026-03-13 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletterpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date_subscribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
