# Generated by Django 5.1.6 on 2025-06-28 09:17

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="user_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="product_id",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    ("1", "star1"),
                    ("2", "star2"),
                    ("3", "star3"),
                    ("4", "star4"),
                    ("5", "star5"),
                ],
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
