# Generated by Django 5.1.6 on 2025-07-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_reviews", "0002_rename_user_id_review_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (5, "star5"),
                    (4, "star4"),
                    (3, "star3"),
                    (2, "star2"),
                    (1, "star1"),
                ]
            ),
        ),
    ]
