# Generated by Django 5.1.6 on 2025-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
