# Generated by Django 5.1.6 on 2025-07-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
    ]
