# Generated by Django 5.1.6 on 2025-10-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
