# Generated by Django 5.1.6 on 2025-04-07 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer_addresses", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_payed", models.BooleanField()),
                ("date_ordered", models.DateTimeField()),
                ("date_fulfilled", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("shipping_tracker", models.TextField()),
                (
                    "address_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="customer_addresses.customeraddress",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
