# Generated by Django 5.1.6 on 2025-07-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="address_id",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="customer_id",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="order_id",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_tracker",
        ),
    ]
