# Generated by Django 5.1.6 on 2025-08-29 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_shippingmethod_order_shipping_method"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="max_delivery_time_in_days",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="min_delivery_time_in_days",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.product",
            ),
        ),
    ]
