# Generated by Django 5.1.6 on 2025-09-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_shippingmethod_max_delivery_time_in_days_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_payed",
            new_name="is_paid",
        ),
    ]
