# Generated by Django 5.1.6 on 2025-09-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_rename_is_payed_order_is_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
    ]
