# Generated by Django 5.1.6 on 2025-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
