# Generated by Django 5.1.6 on 2025-04-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_is_sale_product_old_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
