# Generated by Django 5.1.6 on 2025-04-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_sale_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sale_percentage",
        ),
    ]
