# Generated by Django 5.1.6 on 2025-04-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_sale_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
